services:
  - type: web
    name: marketplace
    runtime: php
    plan: free
    buildCommand: "composer install && php artisan migrate --force"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://marketplace.onrender.com  # Cambia por tu URL real luego del deploy
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: marketplace-db.cz20iy2w69ez.us-east-2.rds.amazonaws.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: marketplace
      - key: DB_USERNAME
        value: admin
      - key: DB_PASSWORD
        value: admin-aleja-db
