services:
  - type: web
    name: marketplace
    runtime: php
    repo: https://github.com/ccastanog94/marketplace
    buildCommand: "composer install && php artisan migrate"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://marketplace-64c4.onrender.com

