services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/TU_USUARIO/TU_REPO
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://TU_DOMINIO_RENDER.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: marketplace-db.cz20iy2w69ez.us-east-2.rds.amazonaws.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: marketplace
      - key: DB_USERNAME
        value: admin
      - key: DB_PASSWORD
        value: admin-aleja-db
